apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app1
spec:
    type: NodePort
    selector:
        app: app1
    ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000
       nodePort: 30080
